name: TriggerGenerator

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  trigger:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Trigger Repository Dispatch
        # You may pin to the exact commit or the version.
        # uses: myrotvorets/trigger-repository-dispatch-action@c817e05be28f593dcf8133440bf496cc1bdda637
        uses: myrotvorets/trigger-repository-dispatch-action@1.1.0
        with:
          # A Personal Access Token with repo scope. Do not use GITHUB_TOKEN.
          token: ${{ secrets.CHAINING_PAT }}
          # A repository (owner/repo) to send the dispatch to
          repo: rschreiber/SilverTurtle.BlogGenerator
          # A custom webhook event name
          type: content-updated
          # An optional JSON payload with extra information about the webhook event that your action or worklow may use. Up to 10 top-level properties are allowed
          payload:  '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'


