name: Remote Dispatch Action Initiator

on:
  push:

jobs:
  dispatch-to-generator-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch initiating repository event
        run: |
          curl -X POST https://api.github.com/repos/rschreiber/SilverTurltle.BlogGenerator \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "blog_content_changed", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

