name: Trigger Build Workflow
on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another workflow
        uses: actions/github-script@v4
        with:
          script: |
            const result = await github.actions.createWorkflowDispatch({
              owner: 'rschreiber',
              repo: 'SilverTurltle.BlogGenerator',
              workflow_id: 'build-pipeline.yml',
              ref: 'main'
            });
            console.log(result);
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
